// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDST0xsJcsnKwxLtUg6DtaIjoGyIRs2CJg',
    appId: '1:838620045273:web:411f15a478694f4b3203c8',
    messagingSenderId: '838620045273',
    projectId: 'wasla-6f0f9',
    authDomain: 'wasla-6f0f9.firebaseapp.com',
    storageBucket: 'wasla-6f0f9.firebasestorage.app',
    measurementId: 'G-4D3VF7R3RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD21NTWV2KnfPHILfSlvgbYQCtRxMQeuBI',
    appId: '1:838620045273:android:82f92766233c5e9d3203c8',
    messagingSenderId: '838620045273',
    projectId: 'wasla-6f0f9',
    storageBucket: 'wasla-6f0f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXT4JAj3C4jdr-Z94Og_WuzuBl65HqNo4',
    appId: '1:838620045273:ios:2b6f596169cb16573203c8',
    messagingSenderId: '838620045273',
    projectId: 'wasla-6f0f9',
    storageBucket: 'wasla-6f0f9.firebasestorage.app',
    iosBundleId: 'com.example.wasla',
  );
}
