import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/message_model.dart';

abstract class ChatRemoteDataSource {
  Future<void> sendMessage({
    required String orderId,
    required String senderId,
    required String content,
  });

  Stream<List<MessageModel>> getMessages(String orderId);
}

class ChatRemoteDataSourceImpl implements ChatRemoteDataSource {
  final FirebaseFirestore firestore;

  ChatRemoteDataSourceImpl({required this.firestore});

  @override
  Stream<List<MessageModel>> getMessages(String orderId) {
    return firestore
        .collection('orders')
        .doc(orderId)
        .collection('messages')
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) {
          return snapshot.docs
              .map((doc) => MessageModel.fromDocument(doc))
              .toList();
        });
  }

  @override
  Future<void> sendMessage({
    required String orderId,
    required String senderId,
    required String content,
  }) async {
    final message = MessageModel(
      id: '', // Generated by Firestore
      orderId: orderId,
      senderId: senderId,
      content: content,
      timestamp: DateTime.now(),
    );

    await firestore
        .collection('orders')
        .doc(orderId)
        .collection('messages')
        .add(message.toDocument());
  }
}
